// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIwTq32OEPV7di8xDkAnUpe0_wqjTGNh4',
    appId: '1:774334622287:web:7d4c8d23eeed3d3602d83a',
    messagingSenderId: '774334622287',
    projectId: 'opa-need',
    authDomain: 'opa-need.firebaseapp.com',
    databaseURL: 'https://opa-need-default-rtdb.firebaseio.com',
    storageBucket: 'opa-need.firebasestorage.app',
    measurementId: 'G-RQ3WHJMSKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhog9sBLs3s85TB3wOLnyDAc6bZCFyQz8',
    appId: '1:774334622287:android:54d821bff2fb3cde02d83a',
    messagingSenderId: '774334622287',
    projectId: 'opa-need',
    databaseURL: 'https://opa-need-default-rtdb.firebaseio.com',
    storageBucket: 'opa-need.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi7vUZHDQuZhxJt5Sk9YNni1J0zDzN-_I',
    appId: '1:774334622287:ios:7ebffb6cccb6ca6902d83a',
    messagingSenderId: '774334622287',
    projectId: 'opa-need',
    databaseURL: 'https://opa-need-default-rtdb.firebaseio.com',
    storageBucket: 'opa-need.firebasestorage.app',
    androidClientId: '774334622287-1llg9nhh0cthfimkug6daks8evvho4rg.apps.googleusercontent.com',
    iosClientId: '774334622287-a2ppr54oai6kps1er0if9629md25ueov.apps.googleusercontent.com',
    iosBundleId: 'com.example.opaNeedAdmin',
  );
}
